name: Build Telegram Android

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug
      tags:
        description: 'Tags to run'
        required: false
        type: boolean
        default: false
      abi:
        description: 'Target ABI'
        required: true
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 增加构建超时时间

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          sdkVersion: '34.0.0'
          ndkVersion: '25.2.9519653'
          buildToolsVersion: '34.0.0'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # ----------------- 清理力度加强 -----------------
      - name: Stop Gradle Daemon
        run: ./gradlew --stop # 尝试先停止 Gradle 守护进程

      - name: Clean Gradle cache (Aggressive)
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/daemon/
          rm -rf ~/.gradle/wrapper/
          rm -rf TMessagesProj_App/.gradle #  清理app目录中的.gradle
          find . -name "build" -type d -exec rm -rf {} +  # 删除所有 build 目录
          df -h #  构建前后检查磁盘空间
      - name: Check disk space (Before Build)
        run: df -h

      # ----------------- 构建时减少中间文件 -----------------
        #    尝试关闭一些没必要的任务
      - name: Build APK
        run: ./gradlew assembleRelease -Porg.gradle.configureondemand=false  -PabiFilters=${{ github.event.inputs.abi }}

      - name: Check disk space (After Build)
        run: df -h

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: TMessagesProj_App/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.RELEASE_KEYSTORE }}
          alias: ${{ secrets.RELEASE_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_STORE_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: telegram-android
          path: TMessagesProj_App/build/outputs/apk/release/app-release.apk
